#Sushant Gupta

SRC1 = main.c

SRC2 = DrawTool.c

SRC3 = ListLib.c

OBJ1 = $(SRC1:.c=.o)

OBJ2 = $(SRC2:.c=.o)

OBJ3 = $(SRC3:.c=.o)

EXE = $(SRC1:.c=.e)

HFILES = DrawTool.h ListLib.h

CFLAGS = -g

all : $(EXE)
 
$(EXE): $(OBJ1) $(OBJ2) $(OBJ3)
	gcc $(CFLAGS) $(OBJ1) $(OBJ2) $(OBJ3) -o $(EXE) 

$(OBJ1) : $(SRC1) $(HFILES)
	gcc -c $(CFLAGS) $(SRC1) -o $(OBJ1)
	
$(OBJ2) : $(SRC2) $(HFILES)
	gcc -c $(CFLAGS) $(SRC2) -o $(OBJ2)
	
$(OBJ3) : $(SR3) $(HFILES)
	gcc -c $(CFLAGS) $(SRC3) -o $(OBJ3)
